### ISSUE TITLE
Library source doesn't update on every run

### ISSUE THREAD

**Issue by brandonaut** [boozallen/jenkins-templating-engine#23]
## Expected behavior
Each time a Jenkins job begins, all referenced libraries are updated to the latest from their sources.

## Actual behavior
I have a library source defined the main Jenkins configuration (it's stored in Git). When I trigger a Jenkins job, the console output says that it's pulling the library directly from Git. However, if I then push a change to library repo and re-run the Jenkins job, the library used in the Jenkins job is not updated with the change.

I've noticed that if I change the configured library source to point to a bad URL, then save, then configure it to point back to the correct URL, it seems to force a re-evaluation, for it then pulls the latest version of the library on the next job run.

## System
Jenkins 2.164.2
Templating Engine Plugin 1.1
SCM API Plugin 2.4.1

**Comment by steven-terrana** [comment]
Thanks for opening an issue! 

We'll look into it and get back to you ASAP. 

Under the hood, the templating engine relies on the jenkins scm API for making calls to GitHub so i'll have to see if there's any caching built into the plugin.

**Comment by cokieffebah** [comment]
@brandonaut can I fork the library repo, to troubleshoot this?  thanks

**Comment by steven-terrana** [comment]
@brandonaut - we've identified the cause of this regression and pushed an update.  version 1.1.1 will be available in the update center shortly. 

please verify at your earliest convenience.

**Comment by brandonaut** [comment]
v1.1.1 works for me! Thanks for your quick turnaround!
